kind: Service
apiVersion: v1
metadata:
  name: dcm-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  selector:
    app: dcm
    tier: backend
  ports:
    - name: grpc-mtls
      port: 7900
      targetPort: 7900
      protocol: TCP
    - name: grpc-mtls-hmac
      port: 8900
      targetPort: 8900
      protocol: TCP
    - name: https-mtls-hmac
      port: 7443
      targetPort: 7443
      protocol: TCP
    - name: https-mtls
      port: 8443
      targetPort: 8443
      protocol: TCP
    - name: https-hmac
      port: 9443
      targetPort: 9443
      protocol: TCP
  type: LoadBalancer