apiVersion: apps/v1
kind: Deployment
metadata:
  name: dcm-service
spec:
  selector:
    matchLabels:
      app: dcm
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: dcm
        tier: backend
        track: stable
    spec:
      containers:
        - name: dcm-service
          image: 837432931185.dkr.ecr.ap-northeast-1.amazonaws.com/dcm-service:latest
          ports:
            - name: grpc
              containerPort: 7900
            - name: https
              containerPort: 8443